# Generated by Django 6.0.1 on 2026-01-28 07:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='fas fa-car', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Car Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField(default=4)),
                ('doors', models.PositiveIntegerField(default=4)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('semi-automatic', 'Semi-Automatic')], default='automatic', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='petrol', max_length=20)),
                ('drive_type', models.CharField(choices=[('2wd', '2 Wheel Drive'), ('4wd', '4 Wheel Drive')], default='2wd', max_length=10)),
                ('engine_capacity', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('air_conditioning', models.BooleanField(default=True)),
                ('bluetooth', models.BooleanField(default=True)),
                ('gps', models.BooleanField(default=False)),
                ('child_seat', models.BooleanField(default=False)),
                ('sunroof', models.BooleanField(default=False)),
                ('features', models.TextField(blank=True, help_text='Comma-separated extra features')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='cars/main/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='cars/thumbnails/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.carcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, help_text='Optional destination e.g. Kampala', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fuel_included', models.BooleanField(default=False)),
                ('driver_included', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Any special conditions')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='cars.car')),
                ('trip_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='cars.triptype')),
            ],
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_available', 'is_featured'], name='cars_car_is_avai_3b2fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['category'], name='cars_car_categor_be58ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carrate',
            unique_together={('car', 'trip_type', 'destination', 'fuel_included')},
        ),
    ]
