# Generated by Django 6.0.1 on 2026-01-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rental price per day in USD.', max_digits=8),
        ),
    ]
