# Generated by Django 6.0.1 on 2026-01-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_price_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price_per_day',
        ),
    ]
