# Generated by Django 6.0.1 on 2026-01-31 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_price_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='main_image',
        ),
    ]
