# Generated by Django 6.0.1 on 2026-03-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_driver_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_user_id_69a5d5_idx',
            old_name='bookings_bo_user_id_5a450c_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_car_id_29d298_idx',
            old_name='bookings_bo_car_id_b812d3_idx',
        ),
    ]
